# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RatedList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RatedList
  pod 'Cosmos', '~> 17.0'

  target 'RatedListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RatedListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
